pipeline {
  agent any
  environment {
        PROJECT = credentials('project_id')
    }
  tools {
    maven 'maven' 
  }
  stages {
    stage('Test Credentials') {
        steps {
            sh 'echo "PROJECT ID: ${PROJECT}"'  // Should print project_id if correct
        }
    }
    stage ('Init') {
      steps {
        sh 'echo "Start of Job"'
        sh 'ls -la'
      }
    }
    stage ('test') {
      steps {
        sh 'mvn clean test -f ./BinaryCalculatorWebapp/pom.xml'
      }
    }
    stage ('build') {
      steps {
        sh 'mvn package -DskipTests -f ./BinaryCalculatorWebapp/pom.xml'
      }
    }
    stage ('Deploy') {
      steps {
        sh 'echo "bye bye"'
      }
    }
  }
}